### ISSUE TITLE
Needs update for 1.18

### ISSUE THREAD

**Issue by robotnikthingy** [InventivetalentDev/AnimatedFrames#235]
Plugin does not seem to work on 1.18, get this error on the server

`08.01 14:36:22 [Server] Server thread/ERROR Could not pass event PlayerInteractEvent to AnimatedFrames v4.13.3-SNAPSHOT

08.01 14:36:22 [Server] INFO org.bukkit.event.EventException: null

08.01 14:36:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]

08.01 14:36:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]

08.01 14:36:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]

08.01 14:36:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]

08.01 14:36:22 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:484) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1534) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3360-Spigot-f65de01-c2e0bbd]

08.01 14:36:22 [Server] INFO at java.lang.Thread.run(Thread.java:833) [?:?]

08.01 14:36:22 [Server] INFO Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.inventivetalent.reflection.minecraft.Minecraft

08.01 14:36:22 [Server] INFO at org.inventivetalent.animatedframes.clickable.ClickListener.on(ClickListener.java:48) ~[?:?]

08.01 14:36:22 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]

08.01 14:36:22 [Server] INFO at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]

08.01 14:36:22 [Server] INFO at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]`

**Comment by ChrissW-R1** [comment]
It works with the latest version 4.13.4-SNAPSHOT (https://github.com/InventivetalentDev/AnimatedFrames/releases/tag/4.13.4-SNAPSHOT)
